server:
  port: 8088
spring:
  application:
    name: service-stream-producer
  cloud:
    stream:
      binders: # 绑定MQ服务信息
        localRabbitBinder: # 给Binder定义的名称，用于后面的关联
          type: rabbit # MQ类型，如果是Kafka的话，此处配置kafka
          environment: # MQ环境配置(用户名、密码等)
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 关联整合通道和binder对象
        output: # output是我们定义的通道名称，此处不能乱改
          destination: wuzxExchange # 要使用的Exchange名称(消息队列主题名称)
          context-type: text/plain # 消息类型设置，比如json
          binder: localRabbitBinder # 关联MQ服务
        input_log:
          destination: wuzxTestExchange
          context-type: text/plain # 消息类型设置，比如json
          binder: localRabbitBinder # 关联MQ服务
        output_log:
          destination: wuzxTestExchange
          context-type: text/plain # 消息类型设置，比如json
          binder: localRabbitBinder # 关联MQ服务

#注册到Eureka服务中心
eureka:
  client:
    service-url:
      # 注册到集群，就把多个Eurekaserver地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: http://localhost:8060/eureka
  instance:
    prefer-ip-address: true # 服务实例显示ip而不是显示主机名
    # 实例名称
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@


# springboot中暴露健康检查等断点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    # 暴露健康接口的细节 endpoint:
    health:
      show-details: always