spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中作为服务的id标识(serviceId)
server:
  port: 8060
eureka:
  instance:
    hostname: localhost
  client:
    service-url: # 客户端与EurekaServer交互的地址，如果是集群，也需要写其它Server的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false # 自己就是服务不需要注册自己
    fetch-registry: false #自己就是服务不需要从Eureka Server获取服务信息,默认为true，置为false

    # register-with-eureka 和 fetch-registry 在单节点时设置为了 false,
    # 因为 只有一台 Eureka Server，并不需要自己注册自己，而现在有了集群，可以在集 群的其他节点中注册本服务

